### ISSUE TITLE
mockup of contact page

### ISSUE THREAD

**Issue by Benfill** [Youcode-Classe-E-2023-2024/Artcode_startup#6]

**Comment by kholoud001** [comment]
- est ce tu peux inverser les couleurs des parties adresse téléphone et email ( background blanc et l'écriture et les icones en bleus)
- et pour le buttons envoyer ( la couleur bleu comme les autres boutons avec l'écriture en blanc)
- inclure le titre About us dans le container bleu ciel 
Merci !!!

**Comment by Benfill** [comment]
good work
